export const queryKeys = {
  workspace: {
    current: ["workspace", "current"] as const,
    projects: ["workspace", "projects"] as const,
    members: (projectId: string) => ["workspace", "project-members", projectId] as const,
  },
  system: {
    health: ["system", "health"] as const,
  },
  repositories: {
    all: ["repositories"] as const,
    list: (projectId: string, params?: { limit?: number; offset?: number }) => ["repositories", "list", projectId, params] as const,
    detail: (repositoryId: string) => ["repositories", "detail", repositoryId] as const,
    snapshots: (repositoryId: string, params?: { limit?: number }) => ["repositories", "snapshots", repositoryId, params] as const,
    snapshotDrift: (repositoryId: string, baseSnapshotId: string, targetSnapshotId?: string) => ["repositories", "snapshot-drift", repositoryId, baseSnapshotId, targetSnapshotId] as const,
  },
  requirements: {
    all: ["requirements"] as const,
    list: (projectId: string) => ["requirements", "list", projectId] as const,
    detail: (requirementId: string) => ["requirements", "detail", requirementId] as const,
  },
  analyses: {
    all: ["impact-analyses"] as const,
    list: (projectId: string, params?: { limit?: number; offset?: number }) => ["impact-analyses", "list", projectId, params] as const,
    detail: (analysisId: string) => ["impact-analyses", "detail", analysisId] as const,
    runs: {
      list: (projectId: string) => ["impact-analyses", "runs", "list", projectId] as const,
      detail: (runId: string) => ["impact-analyses", "runs", "detail", runId] as const,
      mergedReport: (runId: string) => ["impact-analyses", "runs", "merged-report", runId] as const,
      approvedReport: (runId: string) => ["impact-analyses", "runs", "approved-report", runId] as const,
      reviewDecisions: (runId: string) => ["impact-analyses", "runs", "review-decisions", runId] as const,
      latestReviewDecision: (runId: string) => ["impact-analyses", "runs", "latest-review-decision", runId] as const,
      reviewCoverage: (runId: string) => ["impact-analyses", "runs", "review-coverage", runId] as const,
      impactMatrix: (runId: string) => ["impact-analyses", "runs", "impact-matrix", runId] as const,
      impactMatrixRowDetail: (runId: string, analysisId: string) => ["impact-analyses", "runs", "impact-matrix-row-detail", runId, analysisId] as const,
    },
    report: (analysisId: string) => ["impact-analyses", "approved-report", analysisId] as const,
    graph: (analysisId: string) => ["impact-analyses", "graph", analysisId] as const,
    qaCoverage: (analysisId: string) => ["impact-analyses", "qa-coverage", analysisId] as const,
    reviewQueue: (analysisId: string) => ["impact-analyses", "review-queue", analysisId] as const,
    diff: (analysisId: string) => ["impact-analyses", "diff", analysisId] as const,
    driftFreshness: (analysisId: string) => ["impact-analyses", "drift-freshness", analysisId] as const,
    lineage: (analysisId: string) => ["impact-analyses", "lineage", analysisId] as const,
    reviewNotes: (analysisId: string) => ["impact-analyses", "review-notes", analysisId] as const,
    reviewDecisions: (analysisId: string) => ["impact-analyses", "review-decisions", analysisId] as const,
    reviewClarifications: (analysisId: string) => ["impact-analyses", "review-clarifications", analysisId] as const,
    reviewCompletion: (analysisId: string) => ["impact-analyses", "review-completion", analysisId] as const,
    traceability: (analysisId: string) => ["impact-analyses", "traceability", analysisId] as const,
    insights: (analysisId: string) => ["impact-analyses", "insights", analysisId] as const,
  },
  documents: {
    finalReviewedReport: (analysisId: string) => ["documents", analysisId, "final-reviewed-report"] as const,
    documentJobs: (analysisId: string) => ["documents", analysisId, "document-jobs"] as const,
    reviewedReportSnapshot: (analysisId: string) => ["documents", analysisId, "reviewed-report-snapshot"] as const,
  },
  eventLogs: {
    analysis: (analysisId: string) => ["event-logs", "analysis", analysisId] as const,
    scanJob: (repositoryId: string, jobId: string) => ["event-logs", "repository", repositoryId, "scan-job", jobId] as const,
  },
}
