import { z } from 'zod';

export const errorCodeSchema = z.enum([
	'INVALID_PROJECT_NAME',
	'INVALID_REPOSITORY_URL',
	'INVALID_REPOSITORY_REF',
	'DUPLICATE_REQUEST_KEY',
	'REQUEST_KEY_MISMATCH',
	'PROJECT_NOT_FOUND',
	'REPOSITORY_NOT_FOUND',
	'SCAN_JOB_NOT_FOUND',
	'REQUIREMENT_NOT_FOUND',
	'REQUIREMENT_REVISION_NOT_FOUND',
	'INVALID_REQUIREMENT_INPUT',
	'REQUIREMENT_REVISION_NOT_READY',
	'SNAPSHOT_NOT_FOUND',
	'SOURCE_TARGET_NOT_FOUND',
	'SNAPSHOT_PARTIAL_NOT_ALLOWED',
	'ANALYSIS_STALE',
	'IMPACT_ANALYSIS_NOT_FOUND',
	'FINALIZE_REQUIRES_REVIEW_ACK',
	'REVIEW_NOT_ALLOWED',
	'INVALID_EVIDENCE_ORIGIN',
	'INVALID_INSIGHT_CERTAINTY',
	'IMMUTABLE_REVISION',
	'INVALID_SCAN_JOB_STATE',
]);

export type ErrorCode = z.infer<typeof errorCodeSchema>;
