export type AppErrorCode =
  | 'INVALID_PROJECT_NAME'
  | 'INVALID_REPOSITORY_URL'
  | 'INVALID_REPOSITORY_REF'
  | 'DUPLICATE_REQUEST_KEY'
  | 'REQUEST_KEY_MISMATCH'
  | 'PROJECT_NOT_FOUND'
  | 'REPOSITORY_NOT_FOUND'
  | 'SCAN_JOB_NOT_FOUND'
  | 'REQUIREMENT_NOT_FOUND'
  | 'REQUIREMENT_REVISION_NOT_FOUND'
  | 'INVALID_REQUIREMENT_INPUT'
  | 'REQUIREMENT_REVISION_NOT_READY'
  | 'SNAPSHOT_NOT_FOUND'
  | 'SOURCE_TARGET_NOT_FOUND'
  | 'SNAPSHOT_PARTIAL_NOT_ALLOWED'
  | 'ANALYSIS_STALE'
  | 'IMPACT_ANALYSIS_NOT_FOUND'
  | 'IMPACT_ANALYSIS_NOT_RUNNABLE'
  | 'INVALID_AI_EVIDENCE_REFERENCE'
  | 'FINALIZE_REQUIRES_REVIEW_ACK'
  | 'REVIEW_NOT_ALLOWED'
  | 'INVALID_EVIDENCE_ORIGIN'
  | 'INVALID_INSIGHT_CERTAINTY'
  | 'IMMUTABLE_REVISION'
  | 'INVALID_SCAN_JOB_STATE'
  | 'INPUT_PROJECT_MISMATCH'
  | 'INVALID_STATE_TRANSITION'
  | 'APPROVED_REPORT_NOT_FOUND'
  | 'UNSUPPORTED_DOMAIN'
  | 'EMBEDDING_DIMENSION_MISMATCH';

export class AppError extends Error {
  constructor(
    public readonly code: AppErrorCode,
    message: string,
  ) {
    super(message);
  }
}
