export const PDF_REPORT_THEME = {
  colors: {
    text: '#111827',
    textMuted: '#4b5563',
    textSubtle: '#6b7280',
    border: '#d1d5db',
    borderStrong: '#9ca3af',
    surface: '#f9fafb',
    surfaceMuted: '#f3f4f6',
    surfaceSoft: '#eef8ff',
    accent: '#2597d0',
    accentSoft: '#c0eaff',
    success: '#16a34a',
    warning: '#ca8a04',
    danger: '#dc2626',
  },
  font: {
    sans: 'Helvetica',
    sansBold: 'Helvetica-Bold',
    sansItalic: 'Helvetica-Oblique',
    mono: 'Courier',
    monoBold: 'Courier-Bold',
  },
  size: {
    title: 24,
    h1: 17,
    h2: 13.5,
    h3: 11.5,
    body: 10,
    small: 8.5,
    mono: 9,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 18,
    xl: 26,
    xxl: 34,
  },
  page: {
    margins: { top: 42, right: 44, bottom: 48, left: 44 },
  },
  borderRadius: 10,
} as const;
