import { GetFinalReviewedReportUseCase } from './get-final-reviewed-report.usecase';
import { AppError } from '@ba-helper/shared';

describe('GetFinalReviewedReportUseCase', () => {
  let useCase: GetFinalReviewedReportUseCase;
  let getReviewCompletionMock: any;
  let getLatestSnapshotMock: any;
  let prismaMock: any;

  beforeEach(() => {
    getReviewCompletionMock = {
      execute: jest.fn(),
    };
    getLatestSnapshotMock = {
      execute: jest.fn(),
    };
    prismaMock = {
      generatedDocument: {
        findUnique: jest.fn(),
      },
      documentJob: {
        findFirst: jest.fn(),
      },
      impactAnalysis: {
        findUnique: jest.fn(),
      },
    };
    useCase = new GetFinalReviewedReportUseCase(
      getReviewCompletionMock as any,
      getLatestSnapshotMock as any,
      prismaMock as any,
    );
  });

  it('rejects when unreviewed links exist (isComplete is false)', async () => {
    getReviewCompletionMock.execute.mockResolvedValue({
      isComplete: false,
      blockingReasons: ['UNREVIEWED_TRACEABILITY_LINKS'],
    });

    await expect(useCase.execute('analysis-123')).rejects.toThrow(
      new AppError('REVIEW_COMPLETION_REQUIRED' as any, 'Impact analysis review is not complete', {
        blockingReasons: ['UNREVIEWED_TRACEABILITY_LINKS'],
      })
    );

    expect(getLatestSnapshotMock.execute).not.toHaveBeenCalled();
  });

  it('rejects when snapshot missing despite isComplete being true (guard clause)', async () => {
    getReviewCompletionMock.execute.mockResolvedValue({
      isComplete: true,
      blockingReasons: [],
    });
    getLatestSnapshotMock.execute.mockResolvedValue(null);

    await expect(useCase.execute('analysis-123')).rejects.toThrow(
      new AppError(
        'REVIEWED_SNAPSHOT_MISSING' as any,
        'Reviewed report snapshot is missing despite review completion indicating otherwise'
      )
    );
  });

  it('returns approved generated document markdown and snapshot JSON fields unchanged', async () => {
    const mockCompletion = {
      isComplete: true,
      blockingReasons: [],
    };
    const mockSnapshot = {
      id: 'snap-1',
      approvedDocumentId: 'doc-1',
      markdown: null,
      createdAt: new Date('2026-01-01T00:00:00.000Z'),
      reviewDecisionsSnapshot: { some: 'decision data' },
      evidenceQualitySummarySnapshot: { some: 'evidence data' },
      evaluationContextSnapshot: { some: 'eval context' },
      createdByUserId: 'user-1',
    };

    getReviewCompletionMock.execute.mockResolvedValue(mockCompletion);
    getLatestSnapshotMock.execute.mockResolvedValue(mockSnapshot);
    prismaMock.generatedDocument.findUnique.mockResolvedValue({
      id: 'doc-1',
      content: '# Generated Document Markdown',
    });

    const result = await useCase.execute('analysis-123');

    expect(result).toEqual(expect.objectContaining({
      analysisId: 'analysis-123',
      snapshotId: 'snap-1',
      locale: 'en',
      markdown: '# Generated Document Markdown',
      createdAt: '2026-01-01T00:00:00.000Z',
      reviewCompletion: mockCompletion,
      reviewDecisionsSnapshot: { some: 'decision data' },
      evidenceQualitySummarySnapshot: { some: 'evidence data' },
      evaluationContextSnapshot: { some: 'eval context' },
      createdByUserId: 'user-1',
    }));
    expect(result.reviewCoverageSummary).toEqual(expect.objectContaining({
      insights: expect.objectContaining({ total: 0, reviewed: 0 }),
      traceabilityLinks: expect.objectContaining({ total: 0, reviewed: 0 }),
      evidence: expect.objectContaining({ strong: 0, weak: 0, missing: 0 }),
    }));
  });

  it('returns document generated by a completed document job when snapshot is not linked yet', async () => {
    getReviewCompletionMock.execute.mockResolvedValue({
      isComplete: true,
      blockingReasons: [],
    });
    getLatestSnapshotMock.execute.mockResolvedValue({
      id: 'snap-1',
      approvedDocumentId: null,
      markdown: null,
      createdAt: new Date('2026-01-01T00:00:00.000Z'),
      reviewDecisionsSnapshot: [],
      evidenceQualitySummarySnapshot: {},
      evaluationContextSnapshot: null,
      createdByUserId: null,
    });
    prismaMock.documentJob.findFirst.mockResolvedValue({
      id: 'job-1',
      status: 'COMPLETED',
      generatedDocument: { content: '# Job Document' },
    });

    const result = await useCase.execute('analysis-123');

    expect(result.markdown).toBe('# Job Document');
    expect(result.locale).toBe('en');
  });

  it('throws LOCALIZED_REPORT_NOT_READY when localized artifact is missing', async () => {
    getReviewCompletionMock.execute.mockResolvedValue({ isComplete: true, blockingReasons: [] });
    getLatestSnapshotMock.execute.mockResolvedValue({
      id: 'snap-1',
      analysisId: 'analysis-123',
      approvedDocumentId: 'doc-1',
      markdown: null,
      createdAt: new Date(),
    });
    prismaMock.generatedDocument.findUnique.mockResolvedValue({
      id: 'doc-1',
      content: '# English',
    });
    prismaMock.localizedReportArtifact = {
      findUnique: jest.fn().mockResolvedValue(null),
    };

    await expect(useCase.execute('analysis-123', { locale: 'vi-VN' as any })).rejects.toMatchObject({
      code: 'LOCALIZED_REPORT_NOT_READY',
    });
  });

  it('throws LOCALIZED_REPORT_FAILED when localization failed', async () => {
    getReviewCompletionMock.execute.mockResolvedValue({ isComplete: true, blockingReasons: [] });
    getLatestSnapshotMock.execute.mockResolvedValue({
      id: 'snap-1',
      analysisId: 'analysis-123',
      approvedDocumentId: 'doc-1',
      markdown: null,
      createdAt: new Date(),
    });
    prismaMock.generatedDocument.findUnique.mockResolvedValue({ id: 'doc-1', content: '# English' });
    prismaMock.localizedReportArtifact = {
      findUnique: jest.fn().mockResolvedValue({ localizationStatus: 'FAILED' }),
    };

    await expect(useCase.execute('analysis-123', { locale: 'vi-VN' as any })).rejects.toMatchObject({
      code: 'LOCALIZED_REPORT_FAILED',
    });
  });

  it('throws LOCALIZED_REPORT_OUT_OF_SYNC when hashes do not match', async () => {
    getReviewCompletionMock.execute.mockResolvedValue({ isComplete: true, blockingReasons: [] });
    getLatestSnapshotMock.execute.mockResolvedValue({
      id: 'snap-1',
      analysisId: 'analysis-123',
      approvedDocumentId: 'doc-1',
      markdown: null,
      createdAt: new Date(),
    });
    prismaMock.generatedDocument.findUnique.mockResolvedValue({ id: 'doc-1', content: '# English' });
    prismaMock.localizedReportArtifact = {
      findUnique: jest.fn().mockResolvedValue({
        localizationStatus: 'COMPLETED',
        contentMarkdown: '# Vietnamese',
        sourceContentHash: 'old-hash',
      }),
    };
    prismaMock.impactAnalysis.findUnique.mockResolvedValue({ id: 'analysis-123', snapshot: { id: 'snap-1' }, requirementRevision: { id: 'rev-1' } });
    prismaMock.baInsight = { findMany: jest.fn().mockResolvedValue([]) };
    prismaMock.traceabilityLink = { findMany: jest.fn().mockResolvedValue([]) };
    prismaMock.reviewNote = { findMany: jest.fn().mockResolvedValue([]) };
    prismaMock.clarificationItem = { findMany: jest.fn().mockResolvedValue([]) };

    await expect(useCase.execute('analysis-123', { locale: 'vi-VN' as any })).rejects.toMatchObject({
      code: 'LOCALIZED_REPORT_OUT_OF_SYNC',
    });
  });

  it('returns localized markdown when artifact is completed and hashes match', async () => {
    getReviewCompletionMock.execute.mockResolvedValue({ isComplete: true, blockingReasons: [] });
    getLatestSnapshotMock.execute.mockResolvedValue({
      id: 'snap-1',
      analysisId: 'analysis-123',
      approvedDocumentId: 'doc-1',
      markdown: null,
      createdAt: new Date(),
    });
    prismaMock.generatedDocument.findUnique.mockResolvedValue({ id: 'doc-1', content: '# English' });
    prismaMock.impactAnalysis.findUnique.mockResolvedValue({ id: 'analysis-123', snapshot: { id: 'snap-1' }, requirementRevision: { id: 'rev-1' } });
    prismaMock.baInsight = { findMany: jest.fn().mockResolvedValue([]) };
    prismaMock.traceabilityLink = { findMany: jest.fn().mockResolvedValue([]) };
    prismaMock.reviewNote = { findMany: jest.fn().mockResolvedValue([]) };
    prismaMock.clarificationItem = { findMany: jest.fn().mockResolvedValue([]) };

    // Compute expected hash for an empty context to mock correctly
    const { computeCanonicalReportHash } = require('@ba-helper/backend-runtime');
    const mockContext = {
      analysis: { id: 'analysis-123', snapshot: { id: 'snap-1' }, requirementRevision: { id: 'rev-1' } },
      locale: 'en',
      insights: [],
      traceabilityLinks: [],
      reviewNotes: [],
      clarifications: [],
    };
    const expectedHash = computeCanonicalReportHash(mockContext);

    prismaMock.localizedReportArtifact = {
      findUnique: jest.fn().mockResolvedValue({
        localizationStatus: 'COMPLETED',
        contentMarkdown: '# Vietnamese Report',
        sourceContentHash: expectedHash,
      }),
    };

    const result = await useCase.execute('analysis-123', { locale: 'vi-VN' as any });
    expect(result.markdown).toBe('# Vietnamese Report');
  });

  it('does not call retrieval/analysis generation dependencies', async () => {
    expect(useCase).toBeDefined();
  });
});
