import { GetFinalReviewedReportUseCase } from './get-final-reviewed-report.usecase';
import { AppError } from '@ba-helper/shared';

describe('GetFinalReviewedReportUseCase', () => {
  let useCase: GetFinalReviewedReportUseCase;
  let getReviewCompletionMock: any;
  let getLatestSnapshotMock: any;
  let prismaMock: any;
  let contextAdapterMock: any;
  let reportBuilderMock: any;

  beforeEach(() => {
    getReviewCompletionMock = {
      execute: jest.fn(),
    };
    getLatestSnapshotMock = {
      execute: jest.fn(),
    };
    prismaMock = {
      generatedDocument: {
        findUnique: jest.fn(),
      },
      documentJob: {
        findFirst: jest.fn(),
      },
      impactAnalysis: {
        findUnique: jest.fn(),
      },
    };
    contextAdapterMock = {
      buildContext: jest.fn(),
    };
    reportBuilderMock = {
      build: jest.fn(),
    };

    useCase = new GetFinalReviewedReportUseCase(
      getReviewCompletionMock as any,
      getLatestSnapshotMock as any,
      prismaMock as any,
      contextAdapterMock as any,
      reportBuilderMock as any,
    );
  });

  it('rejects when unreviewed links exist (isComplete is false)', async () => {
    getReviewCompletionMock.execute.mockResolvedValue({
      isComplete: false,
      blockingReasons: ['UNREVIEWED_TRACEABILITY_LINKS'],
    });

    await expect(useCase.execute('analysis-123')).rejects.toThrow(
      new AppError('REVIEW_COMPLETION_REQUIRED' as any, 'Impact analysis review is not complete', {
        blockingReasons: ['UNREVIEWED_TRACEABILITY_LINKS'],
      })
    );

    expect(getLatestSnapshotMock.execute).not.toHaveBeenCalled();
  });

  it('rejects when snapshot missing despite isComplete being true (guard clause)', async () => {
    getReviewCompletionMock.execute.mockResolvedValue({
      isComplete: true,
      blockingReasons: [],
    });
    getLatestSnapshotMock.execute.mockResolvedValue(null);

    await expect(useCase.execute('analysis-123')).rejects.toThrow(
      new AppError(
        'REVIEWED_SNAPSHOT_MISSING' as any,
        'Reviewed report snapshot is missing despite review completion indicating otherwise'
      )
    );
  });

  it('returns approved generated document markdown and snapshot JSON fields unchanged', async () => {
    const mockCompletion = {
      isComplete: true,
      blockingReasons: [],
    };
    const mockSnapshot = {
      id: 'snap-1',
      approvedDocumentId: 'doc-1',
      markdown: null,
      createdAt: new Date('2026-01-01T00:00:00.000Z'),
      reviewDecisionsSnapshot: { some: 'decision data' },
      evidenceQualitySummarySnapshot: { some: 'evidence data' },
      evaluationContextSnapshot: { some: 'eval context' },
      createdByUserId: 'user-1',
    };

    getReviewCompletionMock.execute.mockResolvedValue(mockCompletion);
    getLatestSnapshotMock.execute.mockResolvedValue(mockSnapshot);
    prismaMock.generatedDocument.findUnique.mockResolvedValue({
      id: 'doc-1',
      content: '# Generated Document Markdown',
    });

    const result = await useCase.execute('analysis-123');

    expect(result).toEqual({
      analysisId: 'analysis-123',
      snapshotId: 'snap-1',
      locale: 'en',
      markdown: '# Generated Document Markdown',
      createdAt: '2026-01-01T00:00:00.000Z',
      reviewCompletion: mockCompletion,
      reviewDecisionsSnapshot: { some: 'decision data' },
      evidenceQualitySummarySnapshot: { some: 'evidence data' },
      evaluationContextSnapshot: { some: 'eval context' },
      createdByUserId: 'user-1',
    });
  });

  it('returns document generated by a completed document job when snapshot is not linked yet', async () => {
    getReviewCompletionMock.execute.mockResolvedValue({
      isComplete: true,
      blockingReasons: [],
    });
    getLatestSnapshotMock.execute.mockResolvedValue({
      id: 'snap-1',
      approvedDocumentId: null,
      markdown: null,
      createdAt: new Date('2026-01-01T00:00:00.000Z'),
      reviewDecisionsSnapshot: [],
      evidenceQualitySummarySnapshot: {},
      evaluationContextSnapshot: null,
      createdByUserId: null,
    });
    prismaMock.documentJob.findFirst.mockResolvedValue({
      id: 'job-1',
      status: 'COMPLETED',
      generatedDocument: { content: '# Job Document' },
    });

    const result = await useCase.execute('analysis-123');

    expect(result.markdown).toBe('# Job Document');
    expect(result.locale).toBe('en');
  });

  it('renders localized markdown from the reviewed snapshot after default document readiness is satisfied', async () => {
    const mockCompletion = {
      isComplete: true,
      blockingReasons: [],
    };
    const mockSnapshot = {
      id: 'snap-1',
      analysisId: 'analysis-123',
      approvedDocumentId: 'doc-1',
      markdown: null,
      createdAt: new Date('2026-01-01T00:00:00.000Z'),
      reviewDecisionsSnapshot: [],
      evidenceQualitySummarySnapshot: {},
      evaluationContextSnapshot: null,
      createdByUserId: null,
    };
    const mockAnalysis = { id: 'analysis-123' };
    const mockContext = { locale: 'vi' };

    getReviewCompletionMock.execute.mockResolvedValue(mockCompletion);
    getLatestSnapshotMock.execute.mockResolvedValue(mockSnapshot);
    prismaMock.generatedDocument.findUnique.mockResolvedValue({
      id: 'doc-1',
      content: '# English persisted document',
    });
    prismaMock.impactAnalysis.findUnique.mockResolvedValue(mockAnalysis);
    contextAdapterMock.buildContext.mockResolvedValue(mockContext);
    reportBuilderMock.build.mockReturnValue('# Bao cao tieng Viet\n```ts\nconsole.log("raw evidence");\n```');

    const result = await useCase.execute('analysis-123', { locale: 'vi' });

    expect(result.locale).toBe('vi');
    expect(result.markdown).toContain('# Bao cao tieng Viet');
    expect(result.markdown).toContain('console.log("raw evidence");');
    expect(contextAdapterMock.buildContext).toHaveBeenCalledWith(mockSnapshot, mockAnalysis, 'vi');
    expect(reportBuilderMock.build).toHaveBeenCalledWith(mockContext);
  });

  it('throws a document readiness error when the async document job is still queued', async () => {
    getReviewCompletionMock.execute.mockResolvedValue({
      isComplete: true,
      blockingReasons: [],
    });
    getLatestSnapshotMock.execute.mockResolvedValue({
      id: 'snap-1',
      approvedDocumentId: null,
      markdown: null,
      createdAt: new Date('2026-01-01T00:00:00.000Z'),
      reviewDecisionsSnapshot: [],
      evidenceQualitySummarySnapshot: {},
      evaluationContextSnapshot: null,
      createdByUserId: null,
    });
    prismaMock.documentJob.findFirst.mockResolvedValue({
      id: 'job-1',
      status: 'QUEUED',
      failedAt: null,
      error: null,
    });

    await expect(useCase.execute('analysis-123')).rejects.toMatchObject({
      code: 'DOCUMENT_JOB_NOT_READY',
      details: {
        documentJobId: 'job-1',
        status: 'QUEUED',
      },
    });
  });

  it('does not call retrieval/analysis generation dependencies', async () => {
    // Verified implicitly because the only dependencies are getReviewCompletion and getLatestSnapshot
    // There are no retrieval or LLM dependencies injected.
    expect(useCase).toBeDefined();
  });
});
